apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-cluster-config
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-config
    verbs:
      - get
