apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-cluster-config-binding
subjects:
  - kind: ServiceAccount
    name: cluster-config-generator
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-cluster-config
