apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster-config-generator
  name: cluster-config-generator
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: cluster-config-generator
  type: ClusterIP
